"""initial schema

Revision ID: dddbbf1eeb84
Revises: 
Create Date: 2026-08-31 11:04:48.735717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dddbbf1eeb84'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create the schema for a new, empty database.

    Existing CrediFresh databases must be validated and stamped at this
    revision; running this initial migration against existing tables is not a
    data-migration strategy.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('rol', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('rol', sa.String(), nullable=False),
    sa.Column('accion', sa.String(), nullable=False),
    sa.Column('entidad', sa.String(), nullable=False),
    sa.Column('entidad_id', sa.Integer(), nullable=True),
    sa.Column('resultado', sa.String(), nullable=False),
    sa.Column('detalles', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('cedula', sa.String(), nullable=False),
    sa.Column('telefono', sa.String(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cedula'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_table('creditos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('plazo_meses', sa.Integer(), nullable=False),
    sa.Column('tasa_interes', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('fecha_evaluacion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creditos_id'), 'creditos', ['id'], unique=False)
    op.create_table('perfiles_financieros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('ingresos_mensuales', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gastos_mensuales', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('otras_obligaciones', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tipo_ingresos', sa.String(), nullable=False),
    sa.Column('actividad_economica', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cliente_id')
    )
    op.create_index(op.f('ix_perfiles_financieros_id'), 'perfiles_financieros', ['id'], unique=False)
    op.create_table('cuotas_amortizacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credito_id', sa.Integer(), nullable=False),
    sa.Column('numero_cuota', sa.Integer(), nullable=False),
    sa.Column('fecha_vencimiento', sa.DateTime(timezone=True), nullable=False),
    sa.Column('monto_cuota', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('capital', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('interes', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('saldo_remanente', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('monto_pagado', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['credito_id'], ['creditos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cuotas_amortizacion_id'), 'cuotas_amortizacion', ['id'], unique=False)
    op.create_table('evaluaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credito_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('cuota_mensual', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('capacidad_mensual', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('motivos', sa.String(), nullable=False),
    sa.Column('fecha_evaluacion', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['credito_id'], ['creditos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluaciones_id'), 'evaluaciones', ['id'], unique=False)
    op.create_table('notificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('credito_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('mensaje', sa.String(), nullable=False),
    sa.Column('leida', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['credito_id'], ['creditos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notificaciones_credito_id'), 'notificaciones', ['credito_id'], unique=False)
    op.create_index(op.f('ix_notificaciones_id'), 'notificaciones', ['id'], unique=False)
    op.create_index(op.f('ix_notificaciones_usuario_id'), 'notificaciones', ['usuario_id'], unique=False)
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credito_id', sa.Integer(), nullable=False),
    sa.Column('cuota_id', sa.Integer(), nullable=False),
    sa.Column('monto_pagado', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fecha_pago', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('metodo_pago', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['credito_id'], ['creditos.id'], ),
    sa.ForeignKeyConstraint(['cuota_id'], ['cuotas_amortizacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagos_id'), 'pagos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Prevent an accidental destructive rollback of the initial schema."""
    raise NotImplementedError(
        "La migración inicial no admite downgrade porque eliminaría datos."
    )
